### ISSUE TITLE
Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by abhimanyud3dx** [adityanaag3/multipage-lwcoss#1]
Uncaught TypeError: Cannot read property 'appendChild' of null
    at about.js:6
    at about.bundle.78a19a0aeb11613e1099.js:24253
    at about.bundle.78a19a0aeb11613e1099.js:24440
index.js:1 Uncaught Error: Iframe has not been created yet.
    at ve (index.js:1)
    at Object.window.__REACT_ERROR_OVERLAY_GLOBAL_HOOK__.iframeReady (index.js:1)
    at Module.<anonymous> (<anonymous>:2:299992)
    at r (<anonymous>:2:110)
    at <anonymous>:2:904
    at <anonymous>:2:915
    at HTMLIFrameElement.e.onload (index.js:1)
index.js:1 Could not get the stack frames of error: Error: Iframe has not been created yet.
    at ve (index.js:1)
    at me (index.js:1)
    at index.js:1
    at index.js:1
index.js:52 [WDS] Live Reloading enabled.
index.js:126 [WDS] Warnings while compiling.
warnings @ index.js:126
index.js:135 Object

adding 
document.querySelector('#profile') && document.querySelector('#profile').appendChild(app);
in about.js fixed the issue

**Comment by adityanaag3** [comment]
Thank you for pointing it out. Fixed it.
